env:
  global:
  # DISCORD_WEBHOOK
  - secure: x27uGBUltnahb6YLZBPPWe/mJHDAXRNZW8d0bgM9CFowJZE9VmcIkLvh/ZWST10TSeY0Ry1TWyGfpQwLJHuD1AmUFI06tKGR3+/wCcjOLoOX4O7oUQAcheVZ/2GCv2QdzO9zX0SQxfKXOAIIVrs6qjylTJuA3ELM1f8QdQ8qnUDiPmpjyqR4o1MDvvqda4Oennh0nZGu1HnbwkRXmSQr+BO9pKA1SZbOK5W0cqTHxX4lZbbo5UT7N6BCjSXolyKjfB5FbtXZWD8onqXuYx6kwt93vkMYmWeLqUCepvY3BDQXMMK+pTiTI0mVKTMHwgyvan9wZqORJ9g5wofoiwkS4faUcNte2+Svz/1Qk+C0JmNw55ja2SVp6E7QRaTAmuYhhHDtwLsL4ukYwYTyd6oSOS5HnRm1KJsL4ggJrHZDeKheKNVKtQcJtFov8DCh4pBqttx3VQM0KypcCT0MEzuJmbI/iggREJU7EWpIhpa1kHaEZHYHGHdg/PDgxkY2lwZXclwyFxtfcL0rCDhri4TuuYjKdF/Th6F5ReWtTo08wFPxTKq+08sMulsB7yt/+zaQ0FQ3YIlR4In9uswHgNfLK1HcIlG89J5T1OnmGg9v5uZDRWER4uwM8NzTkpvpOjGFKs+1KOCcfX/ztxGD4bJ1UYuhPzgagIDjbW8Sgar1ATU=
  # DIGITALOCEAN_ALPHA_SERVER_DROPLET_NAME
  - secure: msZSe8h8/Rk2QrtmxInP1+zMWujEFRQTJn1ku/HNoAzAkqju8vSbpmDB0CmWg4ASn97D7gnZCYhsVBEoLx13u69p9sJpEqsX+juBteP+UtmGJ+ivvOMRCuSWNJmQK+YngsBJygzead77o4RKC7GGTqO4prvPsgmVkkmYtesoVicBKZR4Mzs2R4Y1t2XebRLBNuylQQw2P3UEPL/zXEYz9NDW+iV49W3NbfX3HGydOzRBpw88iFNXqN1wfxCx/X02SwhNVJmELFULgkHQzhSwfBT4CBcGOiKJBu2hgf1JEcFYVsmcoFwSj5YnWlILZ+h64iFkqwTkVOspGshZY3doGv3tX+lFpHIww1RFLWUZnePsfmRi1Jn3VRRQcrkhMmRAQv4PIpg6ieT1CvilZG7E9zAKHBMS6f/qR5lTe1HV4ccnAqVE/vSsvLbEy2uMSd+bA9BiQjy6JM9avba0q9V5sJ72eWUWqXaFkvN9iYrLuelHOJKfeC8vdRHeANzQhkq90v5auXhJHG9jcpmQFbj9DNptNBNQJPwn5kuvDA3w4wvP9lbqxFJkF/tB5wk+X6THUTkz/AufpU4rPL2+rO71eqifBzxkk0gt4Hqmsio7rhayfghlYTMx8EK+rm26i92WO3z73aDoCJj0gKP5PgrEy/oGfULvGDZB0ynHtaXxYeI=
  # DIGITALOCEAN_ALPHA_SERVER_USER
  - secure: lHYJcGXxrn7VL37pT/36m1HWBaP+CQt0dA61Zo+t9pNY4GHws1Nhn06iX5UlWTHvmFfpOmTeKZbY5ksWTSQdIdcHRnDT95Q1mp/wpEm9LL76IT2CaFoSF6lgDeX+1CLTZmuLZd2Mx5kK4nu+k6s8iqKgtSoPyNENuO5OV20LOCc3/rbiPOqb0EBvCc7iim8D9ZC+F/ertD78ylvZemYNthjflymTVXz8imSo1emdEFNYfSrlVU7nKIRZUcE2ua/RPC7PxEuPPGrNNZPJ2RqoOIR4hJECFiZmPTbXDx99tjFI1xxHJ0R7qIrbgFoObUFtN6FlahdHNUipes6zHtUUAqKDVRFxlQ+xdcPY1wGDTACCCSbg8ySL+HfKUWa2LiAEfTRi54NvVKMWPDRRGHjTlPyzE+bqYKcJgkZjzFVv1eeKkec9t+tStSG8DGrO251SbyH6fPQRYREcJyXT4iRiYIDKwtnb3g8ziWCwN8x79y5xWA+Oy/8RmhSmgTIUIoq6Q7Rg4nWXSTzjdyvSPlqvbQKuCL+Ce1yFl8IytW7BKC53fg73zJtlYVQb4oPHWkry9GZp4qS1Aj4JzFHqfm3yBJvHrJ1HyjS1S+KsM2OLFWmJL4F1MJTwiARiNDilhhi3mMr98oSDgwLPVDmtl4NObqBewkX/G0QU+oYx8dnTuh8=
  # DIGITALOCEAN_ACCESS_TOKEN
  - secure: Cvczli2QXTNwU7mzsslAB4SCTj5ZiMXX14uPrazR2ggXA8KrFIpt+lQj6EQ5AVpI/nr9P1KuasQPSYGn14IWdDYOGWGwPUFWQpxsTAdv7y+C2cJlZfDmkTH38cUXoudkq+LqXfWdfMFxt5WaVmqdWfov3ENP4yHZazRaq4VjdPuzxm79WQpdXY0VYCqO0m+6cNA3bqzMquTC/pRxdOticBJraGz2Frhz78m0ZsSN3nn1fUdgEwlpeyMGgiGCP9/V/bb5iw15X1JguFf+GcKsMFufWuAPcg16BvfhTpLbKs9pmfBb1itYFKvlCVJV/jGF5ifQ48iNiy+6c9wvRoL9kDGrfDMFiV9qrI/v3zkCAu1n0xsV54iyDnnLLWUTrnVazTwMed3lbgWMyOtGDwOgs4TnxjN4MXIJCMeYefde1DO5mkES8lSCQ+hXFucjK9g3B4lrI5vEvFrTvDou2F3uNSPkA/Pjr89tlkOsH83mMk7fr+m/MkyCwabh5NNMB/qB5nud6LkiBgdWYuhWGksPgDdqXU10q2YOudzfMvs7Xq/640UAMKwsdBlpXj5N4ocnaeTMbrty1ExMlPBwHQIEIlhzALZnTq/FocRiQT+HUfNcF1I5IXAM7U+kMq9vL0cPzdOuPh4P6vxfxCrSdkFmEbf8SkfJ5HuQj44PzpifC9w=
  # DIGITAL_OCEAN_HOST
  - secure: pbxU3h3DVHkOXlQYj2Mx63SbJKUN7SMtA3lXsmWURut5aAxOX37rKbl7lPUNKeIkUsCwcWN3MscVtj26Fv9lxaz0WUf6qSazwIPueBBacQ2QC3t3TtyewdvxbDe1GRvF1ZdOs7nbQVPEYf6egsD4EGN23W6lQKPTJrnDmsCDqSPeQUlzHh+mq66UVab3XDEdc+1HDabhfHxuRjSMFwjn51nx7mxwK5bQD/BzfgI5CZe4eVYs5IZ1aNx92T5bpUgT6icAtCA293mKeVRHeRM2UAlPmI8GGogi8e5tAkhTUMLCECjIAY5qaXhTIgUGkECcGCW7iOFBfymfNR3EsN7wEUOxWUwoFVRQISao896ck6yjrg3XItqlrUNGGjRk18ccBpk2LUN0bxjN14bhI7Uk3GaWg9ysX03KRn4vML68+hiLHnoVIdCVxQkOgFOAzL/nHpJAz2rqIjW9+hf2clPWSD8NM2NMcMJhbO+5RN+dEkmo5RZXnYeXu3NxlFE8BUHEUsdvd2WGY3CaTcck+xey/RYsZ4vgj8cVv7deUhPAf/YO4wQ7yx+DBVKO7MtjPZYrUQo+JyafP+V2g13L0RM0Lu57ZDF6WccuwWXoxYWO3gUXMwVV7K86PZGBIvIU5by/Xz/m/vKhAwJ6sdCcpT+mkigwDp4wbjmIT6lO2jLtlXU=
  # SECRET
  - secure: "Xnbd0sTkr30NF/IPozUZs5Uks8V7uizIfuIoERUXy7IN4FfBuc+x+v2HR4Unho8eFh6TNDB3LA+b28Ce4aEajrxuVablLunBTLy/z48A5cyDg8dK2mXEA2iBLYTNei4BT+OBABHtmYd9uEmVTzeq07GPsb2N83LqIwSVAjZSuVJlVgT3a+j1fQrlTE3IjhgM+MaEYR8OaM/+tde5/TH3+lhBM7k71Jfw4a/no7VC1T9fnZ5MlpzZT4rqvl0OgesLrpRnyWlgbPrnrUZRR8h6+p/On9G1Azg5bF8UAfdZloez05zCT54u69tHiA6UdY24ytZtnlgcQmJ40k/NYitjzgiuJ9d7NN1YRhx5qApXdwYrt7D+9ElKuIORMnOIOe9uiUs/MlQ0Llbu51oPUUj/vUYUvhXU1XBY7yvgV1pWB6klW+xXMK+wNd+fze2EHotr0y7DX7+441OohwVC5YIFahdD4rTjHpEqolAhEH6j5y4/T0Gx/jcT/TJKUwPeR3/q71k5OxtRSgtNdxSlZnmAKLEiexS7lGkyE4/dfzxuqxzlyXaGDeAXcduwKs9H4SbZXPjMMIH4KSoOjMw3FMNyN2xJsdi/+fLqq9DAwQLgleRM0bLQCzQfRSjUzqV+6TfYGLBkqRNh8vlFy1orrebnzhVz11RO2FtGhy8tMdhCRyA="
matrix:
  include:
  # basic docker build test
  - if: tag IS blank
    os: linux
    #before_install:
    #- openssl aes-256-cbc -k "$SECRET" -in .env.enc -out server/.env -d
    script:
    - docker-compose build
  # server deploy alpha
  - if: tag =~ -alpha\+server
    os: linux
    before_install:
    #- openssl aes-256-cbc -k "$SECRET" -in .env.enc -out server/.env -d
    - openssl aes-256-cbc -k "$SECRET" -in ssh_key.enc -out ssh_key -d
    - openssl aes-256-cbc -k "$SECRET" -in ssh_key.pub.enc -out ssh_key.pub -d
    script:
    - docker-compose build
    - docker build -t doctl --build-arg SSH_KEY="$(cat ./ssh_key)" --build-arg SSH_KEY_PUB="$(cat ./ssh_key.pub)" --build-arg HOST_IP="${DIGITAL_OCEAN_HOST}" - < ./doctl
    - docker run --rm -e DIGITALOCEAN_ACCESS_TOKEN="${DIGITALOCEAN_ACCESS_TOKEN}" doctl compute ssh ${DIGITALOCEAN_ALPHA_SERVER_DROPLET_NAME} --ssh-user ${DIGITALOCEAN_ALPHA_SERVER_USER} --ssh-command "cd ~/democracy-development && ./start-production.sh $TRAVIS_TAG"
    after_success:
    - 'curl -H ''Content-Type: application/json''  -X POST -d "{\"content\":\"SUCCESS: New Server Alpha Version $TRAVIS_TAG deployed!\"}" ${DISCORD_WEBHOOK}'
    after_failure:
    - 'curl -H ''Content-Type: application/json''  -X POST -d "{\"content\":\"FAILURE: Deploying new Server Alpha Version $TRAVIS_TAG failed!\"}" ${DISCORD_WEBHOOK}'
  # android deploy Alpha
  - if: tag =~ -alpha\+client
    os: linux
    language: android
    jdk: oraclejdk8

    before_install:
    - cd client
    - echo y | android update sdk --no-ui --filter build-tools-26.0.1,build-tools-26.0.2,android-26,extra-android-m2repository
    - openssl aes-256-cbc -k "$SECRET" -in .env.production.enc -out .env.production -d
    - openssl aes-256-cbc -k "$SECRET" -in android/Google_Play_Android_Developer.json.enc -out android/Google_Play_Android_Developer.json -d
    - openssl aes-256-cbc -k "$SECRET" -in android/app/democracy2-release-key.keystore.enc -out android/app/democracy2-release-key.keystore -d
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet

    install:
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
      # android 23
      - build-tools-23.0.1
      - build-tools-25.0.1
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
      # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    script:
    - cd android && fastlane android alpha
    after_success:
    - "curl -H 'Content-Type: application/json'  -X POST -d \"{\\\"content\\\":\\\"SUCCESS: New Android Alpha Version $TRAVIS_BUILD_NUMBER available!\\\"}\" ${DISCORD_WEBHOOK}"
    after_failure:
    - "curl -H 'Content-Type: application/json'  -X POST -d \"{\\\"content\\\":\\\"FAILURE: Deploying new Android Alpha Version $TRAVIS_BUILD_NUMBER failed!\\\"}\" ${DISCORD_WEBHOOK}"

  # ios deploy alpha
  - if: tag =~ -alpha\+client
    osx_image: xcode9.2
    language: objective-c
    xcode_project: ios/democracyclient.xcodeproj
    xcode_scheme: ios/democracyclientTests

    before_install:
    - cd client
    - openssl aes-256-cbc -k "$SECRET" -in .env.production.enc -out .env.production -d

    install:
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install

    script:
    - fastlane update_fastlane
    - cd ios
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios alpha
    after_success:
    - "curl -H 'Content-Type: application/json'  -X POST -d \"{\\\"content\\\":\\\"SUCCESS: New iOS TestFlight Version $TRAVIS_BUILD_NUMBER available!\\\"}\" ${DISCORD_WEBHOOK}"
    after_failure:
    - "curl -H 'Content-Type: application/json'  -X POST -d \"{\\\"content\\\":\\\"FAILURE: Deploying new iOS TestFlight Version $TRAVIS_BUILD_NUMBER failed!\\\"}\" ${DISCORD_WEBHOOK}"
after_script:
- echo "BUILD FINISHED"
