env:
  global:
  # SECRET
  - secure: "Xnbd0sTkr30NF/IPozUZs5Uks8V7uizIfuIoERUXy7IN4FfBuc+x+v2HR4Unho8eFh6TNDB3LA+b28Ce4aEajrxuVablLunBTLy/z48A5cyDg8dK2mXEA2iBLYTNei4BT+OBABHtmYd9uEmVTzeq07GPsb2N83LqIwSVAjZSuVJlVgT3a+j1fQrlTE3IjhgM+MaEYR8OaM/+tde5/TH3+lhBM7k71Jfw4a/no7VC1T9fnZ5MlpzZT4rqvl0OgesLrpRnyWlgbPrnrUZRR8h6+p/On9G1Azg5bF8UAfdZloez05zCT54u69tHiA6UdY24ytZtnlgcQmJ40k/NYitjzgiuJ9d7NN1YRhx5qApXdwYrt7D+9ElKuIORMnOIOe9uiUs/MlQ0Llbu51oPUUj/vUYUvhXU1XBY7yvgV1pWB6klW+xXMK+wNd+fze2EHotr0y7DX7+441OohwVC5YIFahdD4rTjHpEqolAhEH6j5y4/T0Gx/jcT/TJKUwPeR3/q71k5OxtRSgtNdxSlZnmAKLEiexS7lGkyE4/dfzxuqxzlyXaGDeAXcduwKs9H4SbZXPjMMIH4KSoOjMw3FMNyN2xJsdi/+fLqq9DAwQLgleRM0bLQCzQfRSjUzqV+6TfYGLBkqRNh8vlFy1orrebnzhVz11RO2FtGhy8tMdhCRyA="
  # MATCH_GIT
  - secure: "ihPQK5pjFSM8xsTSl7PZvkktR5utmhbnVO7/4zyfuFZA0XKkZ1h7Kos1Qg/iNtUh504wTXnB/M5On9tfPldhA6uGW6TlNdp03SRA9gp1NCza0SkuAFTWWgfvptaHuFBmwsn2tVCoOcSADETXZK4DrEyzVc6k74UMkHKtlfhT8u5igAnEXOsjYjaFNuTvfus1ejNiL39WVHvLkzisuIPm/puyHCmftC/xuxCNWlPHLtjmXMJCpSW+G1O46odvmOWppl1GKtCD36KmUqI4MdcQ/swumAIUIiXEd2lKwzDsWETWQzEDreqN8mw8mmAxpufcBmKf0KMV3/iRzISFiElEH1AJk3D/b7qC4etvIq1t+yKbEDEOJN20HTaDYeRp4jljfHeDrPgYwa9ch/3u0Ac8iA2w8HFFSWpPra82HWHvmUAPVU41OCanyKzOi03pawgqsyi1MmLYm5rOHk9ve8UnT0o9uXM6QMXLdG8XJThTgXL1uUg9lh+eOHfLvUxp2buUvg4vStp/+PjbapLm1mYelPtvVAsGtlZdRxQo8Q37iSjZ3TxO2pkuTL26DF8+afvQx5kDZVBGbryxabMCudLt/4BDxWg4L8u0Q4vxZJDNhs8xz0UI19YsPU0J+pyumMEM7FBf1RpRd9BEwvg+YTKhnUu2MVUWyhTUoQikZwhxbuI="
  # DIGITALOCEAN_ACCESS_TOKEN
  - secure: "Sb0n6FYEd1LBwLTtU4AmblM4JSxEJU8wwH1uknLAkrQK042Xl0GDveb9qsna1eQCxaOenPneCTtA+w/pPdCanQEKjD7WAxYP7hVGq7Wloug2z5DPl6ZeZfEtGiyN58SSRefQMU+cP6OHmp4lmYpL54npi+oUphhSSYmXj2vLcICVUHSjsX18kpZLxDuYc0QUlueNII7aaLkpKIJkRLId9JNw4JBySOGNtl67bhbT2Wom3Wu7wlD5w/ELy+5Fz+6n0yryFgtWwYlhmzoOwcUeBOxLB3Sv9DuAbFBF+7Yi+x1mDSKPknihoDDN5y2GCTq/yy7FRIGUakPu1JZdOl4T4Jv8FtWTdAovLiDzIV2a6xXcQwqUVAfJTsVjh/N3giWHkPS6kJmDNZxpR/QWNnlozVExAkjMARZ2BcXD/Slm1/5pARXt2nqRYBPkd9hJzjHiIX48wAx7KP0JfLV9X6OPSxHGT8FwF/UFtpPi+ms/pwkgwjMZfuT+WeO7VDNnJuN1Vbs50RdKaOX/ziM/u2JjcXiwFo0AaWn3ciXUKMlUOC+X0mkgh2Osi6xbSK33MtlsYwuqgvL6B30zipnjGfqIm2NJ6l16OUxwEbA98+E6fxGnHWdTLSBpQpa9i0OhATTCInEC1AwMqA9+udbMwNsqSIRYzGMsB/37lO9XKwlPhQc="
matrix:
  sudo: required
  include:
  # ########################
  # TESTING
  # ########################
  # basic docker build test
  - if: tag IS blank
    os: linux
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    script:
    - docker-compose build
  
  # ########################
  # CHECK FOR MASTER
  # ########################
  # client in master?
  - if: type IN (pull_request)
    os: linux
    script:
    - ./.travis/gitbranch.sh -d "./client" -b "origin/master"
  # server in master?
  - if: type IN (pull_request)
    os: linux
    script:
    - ./.travis/gitbranch.sh -d "./server" -b "origin/master"
  # bundestag.io in master?
  - if: type IN (pull_request)
    os: linux
    script:
    - ./.travis/gitbranch.sh -d "./bundestag.io" -b "origin/master"
  # elasticsearch in master?
  - if: type IN (pull_request)
    os: linux
    script:
    - ./.travis/gitbranch.sh -d "./elasticsearch" -b "origin/master"
  
  # ########################
  # DEPLOY INTERNAL
  # ########################
  # server deploy internal
  - if: tag =~ -internal\+server
    os: linux
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    script:
    # build docker-compose
    - docker-compose build
    # build doctl
    - docker build -t doctl --build-arg SSH_KEY="$(cat ./.travis/ssh_key)" --build-arg SSH_KEY_PUB="$(cat ./.travis/ssh_key.pub)" --build-arg HOST_IP="${DIGITAL_OCEAN_INTERNAL_HOST}" - < ./doctl
    # run ssh command using doctl
    - docker run --rm -e DIGITALOCEAN_ACCESS_TOKEN="${DIGITALOCEAN_ACCESS_TOKEN}" doctl compute ssh ${DIGITALOCEAN_INTERNAL_SERVER_DROPLET_NAME} --ssh-user ${DIGITALOCEAN_INTERNAL_SERVER_USER} --ssh-command "cd ~/democracy-development && ./deploy-production.sh $TRAVIS_TAG"
    after_success:
    - ./.travis/discord.sh -t "Success Internal $TRAVIS_TAG" -d "[Server] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - ./.travis/discord.sh -t "Failure Internal $TRAVIS_TAG" -d "[Server] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # android deploy internal
  - if: tag =~ -internal\+client
    os: linux
    language: android
    jdk: oraclejdk8
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    - cd client/android
    - gem update --system
    - bundle install
    - bundle update fastlane
    install:
    - cd ..
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
      # android 23,25,26
      - build-tools-23.0.1
      - build-tools-25.0.0
      - build-tools-25.0.1
      - build-tools-25.0.2
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
      - android-25
      - android-26
      # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    script:
    - cd android && bundle exec fastlane android internal
    after_success:
    - cd ./../../
    - ./.travis/discord.sh -t "Success Internal $TRAVIS_TAG" -d "[Android] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - cd ./../../
    - ./.travis/discord.sh -t "Failure Internal $TRAVIS_TAG" -d "[Android] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # ios deploy internal
  - if: tag =~ -internal\+client
    osx_image: xcode9.2
    language: objective-c
    xcode_project: ios/democracyclient.xcodeproj
    xcode_scheme: ios/democracyclientTests
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    - cd client/ios
    - gem update --system
    - bundle install
    - bundle update fastlane
    install:
    - cd ..
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install
    script:
    - cd ios
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios internal
    after_success:
    - cd ./../../
    - ./.travis/discord.sh -t "Success Internal $TRAVIS_TAG" -d "[iOS] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - cd ./../../
    - ./.travis/discord.sh -t "Failure Internal $TRAVIS_TAG" -d "[iOS] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error

  # ########################
  # DEPLOY ALPHA
  # ########################
  # server deploy alpha
  - if: tag =~ -alpha\+server
    os: linux
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    script:
    - docker-compose build
    - docker build -t doctl --build-arg SSH_KEY="$(cat ./.travis/ssh_key)" --build-arg SSH_KEY_PUB="$(cat ./.travis/ssh_key.pub)" --build-arg HOST_IP="${DIGITAL_OCEAN_ALPHA_HOST}" - < ./doctl
    - docker run --rm -e DIGITALOCEAN_ACCESS_TOKEN="${DIGITALOCEAN_ACCESS_TOKEN}" doctl compute ssh ${DIGITALOCEAN_ALPHA_SERVER_DROPLET_NAME} --ssh-user ${DIGITALOCEAN_ALPHA_SERVER_USER} --ssh-command "cd ~/democracy-development && ./deploy-production.sh $TRAVIS_TAG"
    after_success:
    - ./.travis/discord.sh -t "Success Alpha $TRAVIS_TAG" -d "[Server] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - ./.travis/discord.sh -t "Failure Alpha $TRAVIS_TAG" -d "[Server] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # android deploy alpha
  - if: tag =~ -alpha\+client
    os: linux
    language: android
    jdk: oraclejdk8
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    - cd client/android
    - gem update --system
    - bundle install
    - bundle update fastlane
    install:
    - cd ..
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
      # android 23,25,26
      - build-tools-23.0.1
      - build-tools-25.0.0
      - build-tools-25.0.1
      - build-tools-25.0.2
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
      - android-25
      - android-26
      # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    script:
    - cd android && bundle exec fastlane android alpha
    after_success:
    - cd ./../../
    - ./.travis/discord.sh -t "Success Alpha $TRAVIS_TAG" -d "[Android] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - cd ./../../
    - ./.travis/discord.sh -t "Failure Alpha $TRAVIS_TAG" -d "[Android] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # ios deploy alpha
  - if: tag =~ -alpha\+client
    osx_image: xcode9.2
    language: objective-c
    xcode_project: ios/democracyclient.xcodeproj
    xcode_scheme: ios/democracyclientTests
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    - cd client/ios
    - gem update --system
    - bundle install
    - bundle update fastlane
    install:
    - cd ..
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install
    script:
    - cd ios
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios alpha
    after_success:
    - cd ./../../
    - ./.travis/discord.sh -t "Success Alpha $TRAVIS_TAG" -d "[iOS] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - cd ./../../
    - ./.travis/discord.sh -t "Failure Alpha $TRAVIS_TAG" -d "[iOS] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  
  # ########################
  # DEPLOY BETA
  # ########################
  # server deploy beta
  - if: tag =~ -beta\+server
    os: linux
    before_install:
    # ensure we are on the master branch
    - ./.travis/gitbranch.sh -d "./" -b "origin/master"
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    script:
    # build docker-compose
    - docker-compose build
    # build doctl
    - docker build -t doctl --build-arg SSH_KEY="$(cat ./.travis/ssh_key)" --build-arg SSH_KEY_PUB="$(cat ./.travis/ssh_key.pub)" --build-arg HOST_IP="${DIGITAL_OCEAN_BETA_HOST}" - < ./doctl
    # run ssh command using doctl
    - docker run --rm -e DIGITALOCEAN_ACCESS_TOKEN="${DIGITALOCEAN_ACCESS_TOKEN}" doctl compute ssh ${DIGITALOCEAN_BETA_SERVER_DROPLET_NAME} --ssh-user ${DIGITALOCEAN_BETA_SERVER_USER} --ssh-command "cd ~/democracy-development && ./deploy-production.sh $TRAVIS_TAG"
    after_success:
    - ./.travis/discord.sh -t "Success Beta $TRAVIS_TAG" -d "[Server] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - ./.travis/discord.sh -t "Failure Beta $TRAVIS_TAG" -d "[Server] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # android deploy beta
  - if: tag =~ -beta\+client
    os: linux
    language: android
    jdk: oraclejdk8
    before_install:
    # ensure we are on the master branch
    - ./.travis/gitbranch.sh -d "./" -b "origin/master"
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    - cd client/android
    - gem update --system
    - bundle install
    - bundle update fastlane
    install:
    - cd ..
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
      # android 23,25,26
      - build-tools-23.0.1
      - build-tools-25.0.0
      - build-tools-25.0.1
      - build-tools-25.0.2
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
      - android-25
      - android-26
      # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    script:
    # build android & publish using fastlane
    - cd android && bundle exec fastlane android beta
    after_success:
    - cd ./../../
    - ./.travis/discord.sh -t "Success Beta $TRAVIS_TAG" -d "[Android] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - cd ./../../
    - ./.travis/discord.sh -t "Failure Beta $TRAVIS_TAG" -d "[Android] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # ios deploy beta
  - if: tag =~ -beta\+client
    osx_image: xcode9.2
    language: objective-c
    xcode_project: ios/democracyclient.xcodeproj
    xcode_scheme: ios/democracyclientTests
    before_install:
    # ensure we are on the master branch
    - ./.travis/gitbranch.sh -d "./" -b "origin/master"
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    - cd client/ios
    - gem update --system
    - bundle install
    - bundle update fastlane
    install:
    - cd ..
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install
    script:
    # build ios and publish using fastlane
    - cd ios
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios beta
    after_success:
    - cd ./../../
    - ./.travis/discord.sh -t "Success Beta $TRAVIS_TAG" -d "[iOS] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - cd ./../../
    - ./.travis/discord.sh -t "Failure Beta $TRAVIS_TAG" -d "[iOS] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error

  # ########################
  # DEPLOY PRODUCTION
  # ########################
  # server deploy production
  - if: tag =~ -production\+server
    os: linux
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    # ensure we are on the master branch - this does not work for some reason???
    #- ./.travis/gitbranch.sh -d "./" -b "origin/master" -r true
    script:
    - ./.travis/deploy.digitalocean.sh -h "$DIGITAL_OCEAN_PRODUCTION_HOST" -d "$DIGITALOCEAN_PRODUCTION_SERVER_DROPLET_NAME" -u "$DIGITALOCEAN_PRODUCTION_SERVER_USER"
    after_success:
    - ./.travis/discord.sh -t "Success Production $TRAVIS_TAG" -d "[Server] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - ./.travis/discord.sh -t "Failure Production $TRAVIS_TAG" -d "[Server] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # android deploy production
  - if: tag =~ -production\+client
    os: linux
    language: android
    jdk: oraclejdk8
    android:
      components:
      - tools
      - platform-tools
      # android 23,25,26
      - build-tools-23.0.1
      - build-tools-25.0.0
      - build-tools-25.0.1
      - build-tools-25.0.2
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
      - android-25
      - android-26
      # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    # ensure we are on the master branch
    #- ./.travis/gitbranch.sh -d "./" -b "origin/master" -r true
    install:
    - ./.travis/update.fastlane.sh -d "android"
    - source ./.travis/install.yarn.sh
    script:
    # build android & publish using fastlane
    - ./.travis/deploy.fastlane.sh -d "android" -l "production"
    after_success:
    - ./.travis/discord.sh -t "Success Production $TRAVIS_TAG" -d "[Android] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - ./.travis/discord.sh -t "Failure Production $TRAVIS_TAG" -d "[Android] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
  # ios deploy production
  - if: tag =~ -production\+client
    osx_image: xcode9.2
    language: objective-c
    xcode_project: ios/democracyclient.xcodeproj
    xcode_scheme: ios/democracyclientTests
    before_install:
    - ./.travis/decrypt.sh
    - source ./.travis/env.sh
    # ensure we are on the master branch
    #- ./.travis/gitbranch.sh -d "./" -b "origin/master" -r true
    install:
    - ./.travis/update.fastlane.sh -d "ios"
    - source ./.travis/install.yarn.sh
    script:
    # build ios and publish using fastlane
    - ./.travis/deploy.fastlane.sh -d "ios" -l "production"
    after_success:
    - ./.travis/discord.sh -t "Success Production $TRAVIS_TAG" -d "[iOS] Deployed Build $BUILD_NUMBER on Tag $TRAVIS_TAG successful" -c info
    after_failure:
    - ./.travis/discord.sh -t "Failure Production $TRAVIS_TAG" -d "[iOS] Deploy Build $BUILD_NUMBER on Tag $TRAVIS_TAG failed" -c error
after_script:
- echo "BUILD FINISHED"