matrix:
    include:
        -   os: linux
            before_install:
                - openssl aes-256-cbc -K $encrypted_fd73522261db_key -iv $encrypted_fd73522261db_iv -in .env.enc -out ./server/.env -d
            script:
                - docker-compose build
        -   if: $TRAVIS_TAG = "alpha_server"
            os: linux
            before_install:
                - openssl aes-256-cbc -K $encrypted_fd73522261db_key -iv $encrypted_fd73522261db_iv -in .env.enc -out ./server/.env -d
            script:
                - docker-compose build
after_script:
  - echo "BUILD FINISHED"