version: '3'
services:
  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:80:80"
      - "${IP:-0.0.0.0}:443:443"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

  bundestagio:
    build: ./bundestag.io
    container_name: bundestagio
    expose:
      - 443
    restart: always
    environment:
      VIRTUAL_HOST: bundestag.io
      LETSENCRYPT_HOST: bundestag.io
      LETSENCRYPT_EMAIL: contact@democracy-deutschland.de
      DB_URL: mongodb://mongodb/bundestagio
      DEMOCRACY_SERVER_WEBHOOK_URL: https://democracy/webhooks/bundestagio/update
      PORT: 443
    networks:
      bundestagio:
        aliases: 
          - "bundestagio"
      default:
    depends_on:
      - mongodb

  democracy:
    env_file: ./server/.env
    build: ./server
    container_name: democracy
    expose:
      - 443
    restart: always
    environment:
      VIRTUAL_HOST: democracy.bundestag.io
      LETSENCRYPT_HOST: democracy.bundestag.io
      LETSENCRYPT_EMAIL: contact@democracy-deutschland.de
      DB_URL: mongodb://mongodb/democracy
      BUNDESTAGIO_SERVER_URL: https://bundestagio/graphql
      PORT: 443
    networks:
      default:
      bundestagio:
        aliases:
          - "democracy"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.6
    container_name: mongodb
    volumes:
      - db_data:/data/db
    restart: always
    networks:
      bundestagio:
        aliases:
          - "mongodb"
    command: mongod --smallfiles
volumes:
  db_data: #/data/mongodb/db


networks:
  default:
    external:
      name: nginx-proxy
  bundestagio: 
    driver: bridge