version: '3'
services:
  bundestagio:
    environment:
      VIRTUAL_HOST: bundestagio.local
      PERIODS: '19'
    entrypoint:
      - yarn
      - dev
    ports:
      - 3100:80
    volumes:
       - ./bundestag.io:/app
    restart: 'no'
    depends_on:
      - mongodb
      - elasticsearch

  democracy:
    environment:
      VIRTUAL_HOST: democracy.local
    entrypoint:
      - yarn
      - dev
    ports:
      - 3000:80
    volumes:
       - ./server/:/app/
    restart: 'no'
    depends_on:
      - mongodb
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      default:
      intern:
        aliases:
          - "elasticsearch" 
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - mongodb

  mongodb:
    ports:
      - 27020:27017
    volumes:
      - /usr/local/mongodb:/data/db